server.port=8083

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-fragrant-unit-ailk0gqi-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=${REDIS_TIMEOUT:5s}

spring.kafka.bootstrap-servers=kafka-877fe57-ordernest.i.aivencloud.com:14046

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.location=${KAFKA_TRUSTSTORE_PATH:/app/ssl/ca.pem}
spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.properties.ssl.keystore.location=${KAFKA_KEYSTORE_PATH:/app/ssl/client.keystore.p12}
spring.kafka.properties.ssl.keystore.password=changeit

app.order.base-url=https://ordernest-order-service.onrender.com
app.kafka.topic.payment-events=payment.events
app.kafka.topic.order-cancelled-events=order.cancelled.events
app.kafka.consumer.order-cancelled-group-id=ordernest-payment-service-order-cancel-consumer
app.jwt.secret=change-me-in-prod-change-me-in-prod-change-me
app.payment.pending-attempt-ttl-seconds=${PAYMENT_PENDING_ATTEMPT_TTL_SECONDS:3600}
app.razorpay.base-url=https://api.razorpay.com
app.razorpay.key-id=${RAZORPAY_KEY_ID:}
app.razorpay.key-secret=${RAZORPAY_KEY_SECRET:}
app.razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:}
