server:
  port: ${PORT:8083}

spring:
  datasource:
    url: jdbc:postgresql://ep-fragrant-unit-ailk0gqi-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require&currentSchema=payments
    username: neondb_owner
    password: npg_vgtaq37FPiRZ
  data:
    redis:
      url: rediss://default:gQAAAAAAAZO9AAIgcDFlN2Y3ZWIxYjYzMDM0ZWM1OTZhZTA0Yzk4ZGJjMTIwYQ@legible-bull-103357.upstash.io:6379
  kafka:
    bootstrap-servers: kafka-877fe57-ordernest.i.aivencloud.com:14046
    properties:
      ssl:
        truststore:
          type: PEM
          location: /app/ssl/ca.pem
        keystore:
          type: PKCS12
          location: /app/ssl/client.keystore.p12
          password: changeit

app:
  order:
    base-url: https://ordernest-order-service.onrender.com
  razorpay:
    key-id: rzp_test_SPxyuKqCKYHW9G
    key-secret: kfoDcMid1ru6z6Y0oictuXjQ
    webhook-secret: 9c7f4e2a8b1d6f3c5a9e7b4d2c1f8a6b
