# Database
DB_URL=jdbc:postgresql://ep-fragrant-unit-ailk0gqi-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require&currentSchema=payments
DB_USERNAME=neondb_owner
DB_PASSWORD=npg_vgtaq37FPiRZ

# Redis
REDIS_HOST=redis-17068.c267.us-east-1-4.ec2.cloud.redislabs.com
REDIS_PORT=17068
REDIS_USERNAME=default
REDIS_PASSWORD=RFR23wWoK8pijGGTiliUYWNHdOYqt2cE

# Kafka
KAFKA_SERVICE_URL=kafka-877fe57-ordernest.i.aivencloud.com:14046
KAFKA_SECURITY_PROTOCOL=SSL
KAFKA_TRUSTSTORE_PATH=/app/ssl/ca.pem
KAFKA_KEYSTORE_PATH=/app/ssl/client.keystore.p12
KAFKA_KEYSTORE_PASSWORD=changeit

# Internal service URLs
ORDER_API_BASE_URL=https://ordernest-order-service.onrender.com

# Kafka topics and groups
PAYMENT_EVENTS_TOPIC=payment.events
ORDER_CANCELLED_EVENTS_TOPIC=order.cancelled.events
ORDER_CANCELLED_EVENTS_CONSUMER_GROUP_ID=ordernest-payment-service-order-cancel-consumer

# Payment
PAYMENT_PENDING_ATTEMPT_TTL_SECONDS=3600
RAZORPAY_BASE_URL=https://api.razorpay.com

# Razorpay
RAZORPAY_KEY_ID=rzp_test_SPxyuKqCKYHW9G
RAZORPAY_KEY_SECRET=kfoDcMid1ru6z6Y0oictuXjQ
RAZORPAY_WEBHOOK_SECRET=9c7f4e2a8b1d6f3c5a9e7b4d2c1f8a6b
